language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    - RUSTDOC_VERSION=nightly
    - secure: ce5jdhP4MvfdHZNo//Yhh94Zf5WiSYUyAqjT0e9H1IGEnWeVftSFnhvTnp3Tg8PHWoyo5YDYtq/gzGLuGvcQX+Ubg/L67/C8kK0G9r4PwNEPmokIUSVRe7Md0/oUgnqjuB4Qb4/HCmeWW9m8FDpb2ckOQnlTh2pIBb1DELsOOKenCWlP77IYqxi93OZd6V66uQLR9vTZw18V/TdaJk5jdPyDCXeJ6B36Wc4uu4oHuIDudU4brIwC6UipBBSbaBEiBB3CtvOLUlRAvPdoak3POae7OZS10SpjjcnFI8kTomdvD4EywVMuPpuHoz46xE0b3CyB9v1nLIoyVZh4sLtuV5ANEjRV0LnqIuQMq5VbNlyNN9j8jZSmIKGKQPvzcbPPtbJIrae6FKoMgz6T0nxYYl228CgdJ244S5n6J9RAjBa7rGb5ldbmCKJcFD9VTTz/1MOP8DgjI2L0VHdOsoMAVt5kJoc8xkLyeD5Q0LTDDDJiAjwBclYv9t+QXGXTym9B1meW/cT18W5ZLxXZ87IMz1w+JK0X/18+7bDvObOjVeYHHZyD6200J375f/6tTxvzqmAIjgi8Y2vuF3WFNvPKvEQ3u01qnMSwpdwQOnO9m+kO9Wbwpi/xpdR48NP4es0dij1RgqC8ZZwX6xEroPsbZmQGmeBpCDn6q5hb2ynRp1M=

notifications:
  email: false
