language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      curl https://stainless-steel.github.io/travis/documentation.sh | bash;
    fi

env:
  global:
    - secure: HUBsZUD32kDWndzWt5qgVtVAl1Ml4kF7T7bxPUPSEJaLiq/sL3HJMPdlFGQJmNDASFTiwdCQvw0fxRlj/bbLD9QM7rBfTSBWePbTu2RWKCSktPYCDTHLn6lS9HexdeXXN6K0BGWR/p3IVmjy9rWhEwSWK8fai2i1N9izW+E0XEPTwGx5iNjgVQjt/fzVMfyOmFAgiVJtk/368GbpCf57Wp9ULGJ7tTH+/c1MXR8YfCULanW9zTzYeg6PIQ3pQZUq5JmQccNT4tO0+d80YQd13dCco2hrQ7uHKDhHHh2NTWCLERPE1DjLKypHo8vz22BrRY+ul8UHtjEtMBxNDdcNSoZQIJrenezyRbcZfn9S1+L6YZylR312FXIuuouG7EmyxwWXbbCSwWK5nyaVBU4DEWnunrE+m+QnSxvG2OLj4lBJPaIlZmq91DA3XmJzfKb0XXV00u9OwGR5DjMZyoT6wbkb5cKiqADH6JeKK8Vn34wlpuOFJowRNyMiMezTYBF63NPc97MuMoZPTRGJeB+rYa4qPUmC096nNUxfwmnYhpIB/0+thWt96+FO5TMM0UqxooYNkGJBruJmo446ad+WIlMGQOUq0FTbAuzBZZR8DTPWRKLjGuYHzQHuEJSRAjAJvlexciMxC6V5l4L4A2t9fmBLd6rhXlO0x5s0ipdUzig=

notifications:
  email: false
