[package]
name = "process"
version = "0.2.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/process"
homepage = "https://github.com/stainless-steel/process"
documentation = "https://stainless-steel.github.io/process"
description = "The package provides means of simulating stochastic processes."

[dependencies]
complex = "*"
czt = "*"
probability = "*"

[dev-dependencies]
assert = "*"
