[package]
name = "stochastic"
version = "0.3.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/stochastic"
homepage = "https://github.com/stainless-steel/stochastic"
documentation = "https://stainless-steel.github.io/stochastic"
description = "The package provides means of simulating stochastic processes."

[dependencies]
complex = "*"
czt = "*"
probability = "*"
random = "*"

[dev-dependencies]
assert = "*"
