[package]
name = "process"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/process"
homepage = "https://github.com/hilbert-space/process"
description = "Process."
